add lecture11
kubota-tk/RaiseTech pull request #9
Opened 2024-09-05 08:09 UTC by kubota-tk

第11回講義の課題提出です。

2024-09-05 15:02 UTC, MasatoshiMizumoto commented on images11/.DS_Store
このファイルは開発に不要なファイルなのでGitで管理しないようにお願いします！！

2024-09-05 15:02 UTC, MasatoshiMizumoto commented on template11/.DS_Store
このファイルは開発に不要なファイルなのでGitで管理しないようにお願いします！！

2024-09-05 15:03 UTC, MasatoshiMizumoto requested changes
コメント入れた通りですが、不要ファイルのpushが無くせれば承認しますので、ご対応お願いします！！

2024-09-07 04:10 UTC, kubota-tk commented
課題の確認をありがとうございます。
不要ファイルを削除し、今後pushで反映されないよう対応しました。
再度確認をお願いします。

2024-09-07 05:27 UTC, MasatoshiMizumoto approved these changes
LGTMです！！

2024-09-07 05:46 UTC, merged